name: Promote to Production

on:
  push:
    paths:
      - 'overlays/staging/kustomization.yaml'

jobs:
  promote:
    uses: kafd-demo/workflows/.github/workflows/deploy.yml@v0.1
    with:
      targetEnvironment: production
