name: Promote to Production
run-name: Deploy to PRODUCTION

on:
  push:
    paths:
      - 'overlays/staging/kustomization.yaml'

jobs:
  a:
    uses: kafd-demo/workflows/.github/workflows/deploy.yml@main
    with:
      sourceEnvironment: staging
      targetEnvironment: production
    secrets:
      GITOPS_PAT: ${{ secrets.GITOPS_PAT }}
