name: Promote to Staging
run-name: Deploy to STAGING

on:
  push:
    paths:
      - 'overlays/test/kustomization.yaml'

jobs:
  a:
    uses: kafd-demo/workflows/.github/workflows/deploy.yml@main
    with:
      sourceEnvironment: test
      targetEnvironment: staging
    secrets:
      GITOPS_PAT: ${{ secrets.GITOPS_PAT }}