name: Promote to Staging

on:
  push:
    paths:
      - 'overlays/test/kustomization.yaml'

jobs:
  promote:
    uses: kafd-demo/workflows/.github/workflows/deploy.yml@v0.1
    with:
      sourceEnvironment: test
      targetEnvironment: staging
