name: Promote to Test

on:
  push:
    paths:
      - 'overlays/dev/kustomization.yaml'

jobs:
  promote:
    uses: kafd-demo/workflows/.github/workflows/deploy.yml@v0.1
    with:
      sourceEnvironment: dev
      targetEnvironment: test
