name: Promote to Test

on:
  push:
    paths:
      - 'overlays/dev/kustomization.yaml'

jobs:
  promote:
    uses: kafd-demo/workflows/.github/workflows/deploy.yml@main
    with:
      sourceEnvironment: dev
      targetEnvironment: test
    secrets:
      GITOPS_PAT: ${{ secrets.GITOPS_PAT }}